### ISSUE TITLE
正常安装后不能运行

### ISSUE THREAD

**Issue by liulsg** [17Retoucher/ComfyUI_Fooocus#16]
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\__init__.py", line 16, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocusNodes.py", line 10, in <module>
    import fooocus_modules.default_pipeline as pipeline
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\default_pipeline.py", line 1, in <module>
    import fooocus_modules.core as core
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\core.py", line 3, in <module>
    from  .patch import patch_all
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\patch.py", line 12, in <module>
    import fooocus_modules.inpaint_worker as inpaint_worker
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\inpaint_worker.py", line 5, in <module>
    from fooocus_modules.util import resample_image, set_image_shape_ceil, get_image_shape_ceil
  File "G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\util.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Fooocus_promptExpansion
   0.0 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus
   0.5 seconds: G:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by 17Retoucher** [comment]
安装缺失组件，已更新
