### ISSUE TITLE
got an unexpected keyword argument 'patch_weights'

### ISSUE THREAD

**Issue by Imadbein46** [17Retoucher/ComfyUI_Fooocus#19]
Hi I get an error message when I update My Comfyui https://github.com/comfyanonymous/ComfyUI/commit/c18a203a8abdd0fce24743a838fe0d0400d8ff09

!!! Exception during processing !!!
[2024-03-21 15:44] Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 299, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, patch_weights=load_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelPatcher.patch_model() got an unexpected keyword argument 'patch_weights'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocusNodes.py", line 266, in fooocus_preKSampler
    pipeline.refresh_everything(
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\default_pipeline.py", line 258, in refresh_everything
    prepare_text_encoder(async_call=True)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\default_pipeline.py", line 214, in prepare_text_encoder
    comfy.model_management.load_models_gpu(
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Fooocus\py\fooocus_modules\patch.py", line 441, in patched_load_models_gpu
    y = comfy.model_management.load_models_gpu_origin(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 436, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 302, in model_load
    self.model_unload()
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 312, in model_unload
    self.model.unpatch_model(self.model.offload_device, unpatch_weights=unpatch_weights)
TypeError: ModelPatcher.unpatch_model() got an unexpected keyword argument 'unpatch_weights'

**Comment by wibur0620** [comment]
同样的报错

**Comment by winjvlee** [comment]
同样的报错

**Comment by niu211** [comment]
一样的报错还没解决
